#!/bin/zsh
# Author: https://github.com/fredericrous
SCRIPT_PATH=`dirname $(realpath -s "$0")`
test -f "$SCRIPT_PATH/../CHERRY_PICK_HEAD" && exit 0
HOOK_NAME=`basename "$0"`
HOOKS_PATH=("$SCRIPT_PATH"/$HOOK_NAME-*)
for i in `git config --get-all hook.skip`; do
    HOOKS_PATH=(${HOOKS_PATH:#*$i*})
done

failed_hooks=()
function wait_all() {
  local exit_code=0
  local children=("$@")
  for job in "${children[@]}"; do
   wait $job
   exit_code_job="$?"
   if [[ $exit_code_job != "0" ]]; then
     exit_code=$exit_code_job;
     failed_hooks=$job
   fi
  done
  return $exit_code
}

typeset -A pids
for f in $HOOKS_PATH; do
    "$f" "$@" &
    pids[$!]="$f"
done

wait_all "${(@k)pids}"
EXIT_CODE="$?"
if [[ $EXIT_CODE -ne 0 ]]; then
    printf "\n🚨  Error raised by:\n"
    for i in $failed_hooks; do
        printf "    - \u001b[38;5;208m${pids[$i]}\u001b[0m\n"
    done
fi
exit $EXIT_CODE
