#!/bin/zsh
# Author: https://github.com/fredericrous
SCRIPT_PATH=$(dirname $(realpath "$0"))
HOOK_NAME=`basename "$0"`
HOOKS_PATH=("$SCRIPT_PATH"/$HOOK_NAME-*)
for i in `git config --get-all hook.skip`; do
    HOOKS_PATH=(${HOOKS_PATH:#*$i*})
done

for f in $HOOKS_PATH; do
    "$f" "$@"
    EXIT_CODE=$?
    if [[ $EXIT_CODE -ne 0 ]]; then
        printf "\n🚨  Error raised by hook \033[38;5;208m$f\033[0m\n"
        exit $EXIT_CODE
    fi
done
