#!/bin/zsh
# Author: https://github.com/fredericrous
SCRIPT_PATH=`dirname $(realpath -s "$0")`
HOOK_NAME=`basename "$0"`

function wait_all() {
  local exit_code=0
  local children=("$@")
  for job in "${children[@]}"; do
   wait $job
   exit_code_job="$?"
   if [[ $exit_code_job != "0" ]]; then
     exit_code=$exit_code_job;
   fi
  done
  return $exit_code
}

pids=()
for f in "$SCRIPT_PATH"/$HOOK_NAME-*; do
    "$f" "$@" &
    pids+=("$!")
done

wait_all "${pids[@]}"
EXIT_CODE="$?"
if [[ $EXIT_CODE -ne 0 ]]; then
    printf "\n🚨  Error raised by hook \u001b[38;5;208m$f\u001b[0m\n"
fi
exit $EXIT_CODE
